### ISSUE TITLE
useR!2018 suggested changes

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/fable-talk-2018#2]
- [x] Condense the comparison between ts and tsibble (slide changes are probably not needed, but no need to talk about it as much)
- [x] ~~Possibly remove the cafe example (the elecdemand demonstrates univariate ARIMA and prison demonstrates ETS)~~
- [x] Highlight the formula based model building interface, not just the automatic model selection (key components: `t(y) ~ specials() + xregs`)
- [x] Talk about the prison example last (this is more about future plans, as reconciliation isn't done yet. Also this example may appear more impressive to the audience than the Arima+xreg example, so could be better to finish with this one.)
- [x] Mention extensibility towards the end as a design goal of fable, as a segue into my talk

@earowang: Can you think of anything that we discussed that I've forgotten here?

**Comment by robjhyndman** [comment]
The cafe example was meant to show how to model a simple ts object for people familiar with the forecast package. It also demonstrates a transformation. So I'd rather leave it in, but do it quickly. Perhaps drop the ETS part, and just show the ARIMA part with the log transform. ETS is demonstrated for the prison data in any case.

I agree with the other comments.
